global:
    scrape_interval: 5s

scrape_configs:
    - job_name: 'spring-boot'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['10.10.99.59:8080']